// Mock data for demo mode
export const mockUser = {
  id: 'demo-user-1',
  email: 'demo@cennygrosz.pl',
  name: 'Demo User',
  created_at: new Date().toISOString(),
};

export const mockWallets = [
  {
    id: 'wallet-1',
    name: 'Mój portfel',
    emoji: '💰',
    balance: 5420.50,
    is_shared: false,
    owner_id: 'demo-user-1',
    members: [],
    members_details: [],
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wallet-2',
    name: 'Wspólny budżet',
    emoji: '🏠',
    balance: 12350.00,
    is_shared: true,
    owner_id: 'demo-user-1',
    members: ['demo-user-2'],
    members_details: [
      {
        id: 'demo-user-2',
        name: 'Anna Kowalska',
        email: 'anna@example.pl',
        joined_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ],
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wallet-3',
    name: 'Oszczędności',
    emoji: '🎯',
    balance: 8900.00,
    is_shared: false,
    owner_id: 'demo-user-1',
    members: [],
    members_details: [],
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockTransactions = [
  {
    id: 'tx-1',
    wallet_id: 'wallet-1',
    user_id: 'demo-user-1',
    user_name: 'Demo User',
    amount: 3500.00,
    type: 'income' as const,
    category: 'Wynagrodzenie',
    emoji: '💰',
    note: 'Pensja za styczeń',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-2',
    wallet_id: 'wallet-2',
    user_id: 'demo-user-2',
    user_name: 'Anna Kowalska',
    amount: 450.00,
    type: 'expense' as const,
    category: 'Zakupy',
    emoji: '🛒',
    note: 'Zakupy spożywcze',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-3',
    wallet_id: 'wallet-1',
    user_id: 'demo-user-1',
    user_name: 'Demo User',
    amount: 89.99,
    type: 'expense' as const,
    category: 'Transport',
    emoji: '🚗',
    note: 'Tankowanie',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-4',
    wallet_id: 'wallet-2',
    user_id: 'demo-user-1',
    user_name: 'Demo User',
    amount: 1200.00,
    type: 'expense' as const,
    category: 'Rachunki',
    emoji: '📄',
    note: 'Czynsz',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-5',
    wallet_id: 'wallet-1',
    user_id: 'demo-user-1',
    user_name: 'Demo User',
    amount: 120.50,
    type: 'expense' as const,
    category: 'Jedzenie',
    emoji: '🍔',
    note: 'Obiad w restauracji',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-6',
    wallet_id: 'wallet-3',
    user_id: 'demo-user-1',
    user_name: 'Demo User',
    amount: 500.00,
    type: 'income' as const,
    category: 'Freelance',
    emoji: '💻',
    note: 'Projekt dodatkowy',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-7',
    wallet_id: 'wallet-2',
    user_id: 'demo-user-2',
    user_name: 'Anna Kowalska',
    amount: 250.00,
    type: 'expense' as const,
    category: 'Rozrywka',
    emoji: '🎬',
    note: 'Kino i kolacja',
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tx-8',
    wallet_id: 'wallet-1',
    user_id: 'demo-user-1',
    user_name: 'Demo User',
    amount: 75.00,
    type: 'expense' as const,
    category: 'Transport',
    emoji: '🚗',
    note: 'Bilet miesięczny',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockGoals = [
  {
    id: 'goal-1',
    user_id: 'demo-user-1',
    name: 'Wakacje w Grecji',
    emoji: '✈️',
    target_amount: 5000.00,
    current_amount: 3200.00,
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'goal-2',
    user_id: 'demo-user-1',
    name: 'Nowy laptop',
    emoji: '💻',
    target_amount: 4500.00,
    current_amount: 1800.00,
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    completed: false,
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'goal-3',
    user_id: 'demo-user-1',
    name: 'Fundusz awaryjny',
    emoji: '🏦',
    target_amount: 10000.00,
    current_amount: 10000.00,
    completed: true,
    created_at: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockCategories = [
  { id: 'cat-1', name: 'Jedzenie', emoji: '🍔', type: 'expense', is_default: true },
  { id: 'cat-2', name: 'Transport', emoji: '🚗', type: 'expense', is_default: true },
  { id: 'cat-3', name: 'Zakupy', emoji: '🛒', type: 'expense', is_default: true },
  { id: 'cat-4', name: 'Rozrywka', emoji: '🎬', type: 'expense', is_default: true },
  { id: 'cat-5', name: 'Rachunki', emoji: '📄', type: 'expense', is_default: true },
  { id: 'cat-6', name: 'Zdrowie', emoji: '💊', type: 'expense', is_default: true },
  { id: 'cat-7', name: 'Inne', emoji: '📌', type: 'expense', is_default: true },
  { id: 'cat-8', name: 'Wynagrodzenie', emoji: '💰', type: 'income', is_default: true },
  { id: 'cat-9', name: 'Freelance', emoji: '💻', type: 'income', is_default: true },
  { id: 'cat-10', name: 'Prezent', emoji: '🎁', type: 'income', is_default: true },
  { id: 'cat-11', name: 'Zwrot', emoji: '↩️', type: 'income', is_default: true },
  { id: 'cat-12', name: 'Inwestycje', emoji: '📈', type: 'income', is_default: true },
  { id: 'cat-13', name: 'Inne', emoji: '💵', type: 'income', is_default: true },
];

export const mockStats = {
  total_balance: 26670.50,
  month_income: 4000.00,
  month_expenses: 2185.49,
  wallets_count: 3,
  goals_progress: [
    {
      id: 'goal-1',
      name: 'Wakacje w Grecji',
      emoji: '✈️',
      progress: 64,
      current: 3200.00,
      target: 5000.00,
    },
    {
      id: 'goal-2',
      name: 'Nowy laptop',
      emoji: '💻',
      progress: 40,
      current: 1800.00,
      target: 4500.00,
    },
  ],
  expense_categories: {
    'Zakupy': 450.00,
    'Rachunki': 1200.00,
    'Jedzenie': 120.50,
    'Transport': 164.99,
    'Rozrywka': 250.00,
  },
};

// Demo mode delay to simulate API calls
export const demoDelay = (ms: number = 500) => new Promise(resolve => setTimeout(resolve, ms));
